#%RAML 1.0 DataType

#This file is located at dataTypes/ErrorResponse.raml

type: object
properties:
  location: string
  time: datetime
  wind: string
  visibility: string
  skyConditions: string
  temperature: string
  dewPoint: string
  relativeHumidity: string
  status: string